### ISSUE TITLE
I am always getting invalid credentials when trying to connect to https://chainfury.nbox.ai/ui/login

### ISSUE THREAD

**Issue by billmetangmo** [NimbleBoxAI/ChainFury#115]
Steps:
Open https://chainfury.nbox.ai/ui/login with firefox/chrome/brave and fill with admin/admin

**Comment by vgulerianb** [comment]
Hey Bill,

Regarding the issue with the admin credentials on https://chainfury.nbox.ai/ui/login, please note that they will not work since it is a demo app. Instead, you can try creating a new account and login using those credentials.

Alternatively, if you prefer, you can run the project on your local machine by following the steps outlined in the Readme.

I hope this information is helpful.

**Comment by billmetangmo** [comment]
@vgulerianb I tried to create an acount then use it for aconnection adn i got the same issue

**Comment by vgulerianb** [comment]
What error are you getting, can you share steps to reproduce the issue.
Also try to login using username(not email) and password

**Comment by billmetangmo** [comment]
Oh this was the issue. Thanks @vgulerianb
